/*CASO 1: Creacion de Roles y Usuarios*/
-- Crear el usuario PRY2205_USER1
CREATE USER PRY2205_USER1 
IDENTIFIED BY "dUoc.2024.ironmaiden"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";

--Creo los sinónimos Privados y publicos
-- privados
CREATE SYNONYM PAGOS 
FOR PRY2205_USER1.PAGOS;
CREATE SYNONYM PACIENTE 
FOR PRY2205_USER1.PACIENTE;
-- Públicos
CREATE PUBLIC SYNONYM PAGOS 
FOR PRY2205_USER1.PAGOS;
CREATE PUBLIC SYNONYM PACIENTE 
FOR PRY2205_USER1.PACIENTE;

--Validar Sinonimos
SELECT * FROM ALL_SYNONYMS WHERE SYNONYM_NAME IN ('PAGOS', 'PACIENTE');

-- Creando Roles ROL_D y ROL_P
CREATE ROLE PRY2205_ROL_D;

-- Asignación de permisos a Rol_P
CREATE ROLE PRY2205_ROL_P;
GRANT CREATE PROCEDURE TO PRY2205_ROL_P;
GRANT CREATE SESSION TO PRY2205_ROL_P; -- Permiso para iniciar sesión
GRANT CREATE TABLE TO PRY2205_ROL_P; -- Permiso para crear tablas
GRANT CREATE VIEW TO PRY2205_ROL_P; -- Permiso para crear vistas
GRANT CREATE SYNONYM TO PRY2205_ROL_P; -- Permiso para crear sinónimos privados
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_P; -- Permiso para crear sinónimos públicos

-- Asignacion de Rol a usuario
GRANT PRY2205_ROL_P TO PRY2205_USER1;
GRANT PRY2205_ROL_D TO PRY2205_USER2;

-- Revisar Privilegios - Solo para comprobacion de asignación
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'PRY2205_USER1';

/*CASO 2: Informe de Pagos*/
CREATE OR REPLACE VIEW v_recalculo_pagos AS
SELECT
    P.RUT || '-' || P.DIGITO_VERIFICADOR AS RUT_PACIENTE
    ,P.SISTEMA_SALUD
    ,P.NOMBRE || ' ' || P.APELLIDO_PATERNO AS NOMBRE_COMPLETO
    ,PAGOS.COSTO_BONO,
    CASE
        WHEN PAGOS.COSTO_BONO BETWEEN 15000 AND 25000 
            THEN ROUND(PAGOS.COSTO_BONO * 1.15)
        WHEN PAGOS.COSTO_BONO > 25000 
            THEN ROUND(PAGOS.COSTO_BONO * 1.2)
        ELSE PAGOS.COSTO_BONO
    END AS MONTO_A_CANCELAR,
    P.EDAD
FROM PRY2205_USER2.PAGOS AS PAGOS
INNER JOIN PRY2205_USER2.PACIENTE AS P ON PAGOS.ID_PACIENTE = P.ID_PACIENTE
WHERE PAGOS.HORA_ATENCION > '17:15:00';

/*CASO 3: Vista de aumento de Sueldos*/
CREATE OR REPLACE VIEW VISTA_AUM_MEDICO_X_CARGO AS
SELECT
    M.RUT || '-' || M.DIGITO_VERIFICADOR AS RUT_MEDICO,
    M.CARGO,
    M.SUELDO_BASE,
    ROUND(M.SUELDO_BASE * 1.15, 0) AS SUELDO_AUMENTADO
FROM PRY2205_USER1.MEDICO AS M
WHERE UPPER(M.CARGO) LIKE '%ATENCIÓN%';

/*Casos 3: Optimizacion para Caso Específico*/
CREATE OR REPLACE VIEW VISTA_AUM_MEDICO_X_CARGO_2 AS
SELECT
    M.RUT || '-' || M.DIGITO_VERIFICADOR AS RUT_MEDICO,
    M.CARGO,
    M.SUELDO_BASE,
    ROUND(M.SUELDO_BASE * 1.15, 0) AS SUELDO_AUMENTADO
FROM PRY2205_USER1.MEDICO AS M
WHERE M.CARGO = '400' AND M.SUELDO_BASE < 1500000;

/*Optimizacion de indices*/
CREATE INDEX idx_medico_cargo ON PRY2205_USER1.MEDICO(CARGO);
CREATE INDEX idx_pago_fecha ON PRY2205_USER2.PAGOS(HORA_ATENCION);
